name: "Create Executables"

on:
  push:
    branches:
      - "dev"

jobs:
  # Creating a Windows Executable and uploading the artifact works
  create-windows-exe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: "Create Windows Executable"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          HYPERATE_API_KEY: ${{ secrets.HYPERATE_API_KEY }}
      - run: npm install
      - run: npm run build-win --if-present

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: HypeRate-Win.tpp
          path: base/Win/HypeRate-Win.tpp

  # Creating a Max Executable and uploading the artifact works
  create-mac-exe:
    needs: create-windows-exe
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: "Create Mac Executable"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          HYPERATE_API_KEY: ${{ secrets.HYPERATE_API_KEY }}
      #      - run: sed -i '' 's/${process.env.HYPERATE_API_KEY}/${{ secrets.HYPERATE_API_KEY }}/g' dist/index.js
      - run: npm install
      - run: npm run build-mac --if-present

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: HypeRate-Mac.tpp
          path: base/Mac/HypeRate-Mac.tpp
