name: "Create Executables"

on:
  push:
    branches: ["dev"]

jobs:
  create-windows-exe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Create Windows Executable
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build-win --if-present

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v1
        with:
          name: windows-exe
          path: Installers/TouchPortalHypeRatePlugin-Windows.tpp

  create-mac-exe:
    needs: create-windows-exe
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Create Mac Executable
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build-mac --if-present

      - name: Upload Mac Executable
        uses: actions/upload-artifact@v1
        with:
          name: mac-exe
          path: Installers/TouchPortalHypeRatePlugin-Mac.tpp

  release:
    needs: create-mac-exe
    runs-on: ubuntu-latest

    steps:
      - name: Download Executables
        uses: actions/download-artifact@v1

      - name: Create Release
        id: create_release
        uses: actions/create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}

      - name: Upload Windows Asset
        id: upload_windows_release_asset
        uses: actions/upload-release-assets@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows-exe/TouchPortalHypeRatePlugin-Windows.tpp
          asset_name: HypeRate-Windows.tpp
          asset_content_type: application/zip

      - name: Upload Mac Asset
        id: upload_mac_release_asset
        uses: actions/upload-release-assets@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mac-exe/TouchPortalHypeRatePlugin-Mac.tpp
          asset_name: HypeRate-Mac.tpp
          asset_content_type: application/zip
